University/Controllers/CourseController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using SendGrid.Helpers.Errors.Model;
using University.Models;
using University.Services.Interface;
using University.ViewModels;

namespace University.Controllers
{
    public class CourseController : Controller
    {
        private ICourseService _courseService;
        private IMapper _mapper; 

        public CourseController(ICourseService courseService, IMapper mapper)
        {            
            _courseService = courseService ?? throw new ArgumentNullException(nameof(courseService));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }
       
        public IActionResult Index(string searchString, int? pageNumber)
        {            
            return View(PaginatedList<Course>.CreateAsync(_courseService.IndexCourseLogic(searchString), pageNumber ?? 1, _courseService.CoursePageSize()));
        }
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("CourseId,CourseName")] Course course)
        {
            if (ModelState.IsValid)
            {
                _courseService.CourseCreate(course);
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }
        
        public IActionResult Edit(int id)
        {
            var config = new MapperConfiguration(cfg => cfg.CreateMap<Course, CourseViewModel>());
            var map = new Mapper(config);

            var course = _courseService.GetCourseById(id);
            var model = _mapper.Map<CourseViewModel>(course);
            return View(model);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("CourseId,CourseName")] Course course)
        {           
            if (ModelState.IsValid)
            {
                _courseService.UpdateCourse(course);
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }  
        
        public IActionResult Delete(int id)
        {
            var course = _courseService.GetCourseById(id);
            var model = _mapper.Map<CourseViewModel>(course);
            return View(model);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            try
            {
                _courseService.CourseDelete(id);
            }
            catch (NotFoundException)
            {
                return RedirectToAction(nameof(DeleteResult));
            }

            return RedirectToAction(nameof(Index));
        }
        private IActionResult DeleteResult()
        {
            return View();
        }

        private bool CourseExists(int id)
        {
            return (_courseService.GetAllCourses()?.Any(e => e.CourseId == id)).GetValueOrDefault();
        }
    }
}

University/Controllers/GroupController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SendGrid.Helpers.Errors.Model;
using University.Models;
using University.Services.Interface;
using University.ViewModels;

namespace University.Controllers
{
    public class GroupController : Controller
    {                    
        private IGroupService _groupService;
        private IMapper _mapper;

        public GroupController(IGroupService groupService, IMapper mapper)
        {                                  
            _groupService = groupService ?? throw new ArgumentNullException(nameof(groupService));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }       

        public IActionResult Index(int? id, string searchString, int? pageNumber)
        {                           
            return View(PaginatedList<Group>.CreateAsync(_groupService.IndexGroupLogic(id, searchString), pageNumber ?? 1, _groupService.GroupPageSize()));
        }             
        
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("GroupId,CourseId,GroupName")] Group @group)
        {
            if (ModelState.IsValid)
            {               
                _groupService.GroupCreate(@group);
                return RedirectToAction(nameof(Index));
            }
            return View(@group);
        }
        
        public IActionResult Edit(int id)
        { 
            var group = _groupService.GetGroupById(id);
            var model = _mapper.Map<GroupViewModel>(group);
            return View(model);
        }
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("GroupId,CourseId,GroupName")] Group @group)
        {           
            if (ModelState.IsValid)
            {
                _groupService.UpdateGroup(@group);
                return RedirectToAction(nameof(Index));
            }
            return View(@group);
        }
        
        public IActionResult Delete(int id)
        {
            var group = _groupService.GetGroupById(id);
            var model = _mapper.Map<GroupViewModel>(group);
            return View(model);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {         
            try
            {
                _groupService.GroupDelete(id);
            }
            catch (NotFoundException)
            {
                return RedirectToAction(nameof(DeleteResult));
            }
            
            return RedirectToAction(nameof(Index));
        }

        private IActionResult DeleteResult()
        {
            return View();
        }

        private bool GroupExists(int id)
        {
          return (_groupService.GetAllGroups()?.Any(e => e.GroupId == id)).GetValueOrDefault();
        }
    }
}

University/Controllers/StudentController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using University.Models;
using University.Services.Interface;
using University.ViewModels;

namespace University.Controllers
{
    public class StudentController : Controller
    {                   
        private IStudentService _studentService;
        private IMapper _mapper;

        public StudentController(IStudentService studentService, IMapper mapper)
        {
            _studentService = studentService ?? throw new ArgumentNullException(nameof(studentService));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }
        
        public IActionResult Index(int? id, string searchString, int? pageNumber)
        {            
            return View(PaginatedList<Student>.CreateAsync(_studentService.IndexStudentLogic(id, searchString), pageNumber ?? 1, _studentService.StudentPageSize()));
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("StudentId,GroupId,StudentName")] Student student)
        {
            if (ModelState.IsValid)
            {
                _studentService.StudentCreate(student);
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        public IActionResult Edit(int id)
        {
            var student = _studentService.GetStudentById(id);
            var model = _mapper.Map<StudentViewModel>(student);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("StudentId,GroupId,StudentName")] Student student)
        {           

            if (ModelState.IsValid)
            {
                _studentService.UpdateStudent(student);
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        public IActionResult Delete(int id)
        {
            var student = _studentService.GetStudentById(id);
            var model = _mapper.Map<StudentViewModel>(student);
            return View(model);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _studentService.StudentDelete(id);
            return RedirectToAction(nameof(Index));
        }

        private bool StudentExists(int id)
        {
          return (_studentService.GetAllStudents()?.Any(e => e.StudentId == id)).GetValueOrDefault();
        }
    }
}

University/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - University</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/University.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Course" asp-action="Index" asp-route-id="null" >Courses</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Group" asp-action="Index" asp-route-id="null">Group </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Student" asp-action="Index" asp-route-id="null">Student</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - University - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>